### PR TITLE
feat: add cbr zones to the base account module

### PR DESCRIPTION
**Pull request by MatthewLemmond**
### Description
Add the ability to create CBR zones via the CBR zone module in the base IAM account module.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Added the ability to create CBR zones to the account when calling the module using the terrafrom-ibm-cbr zones submodule

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Ak-sky** [comment]
Are we not creating any CBR rules here?

**Comment by MatthewLemmond** [comment]
@Ak-sky no, this is just meant to be run to set the account-level settings for zones as another way to control access, but is not meant for service-level restrictions/accesses

**Comment by Ak-sky** [comment]
> @Ak-sky no, this is just meant to be run to set the account-level settings for zones as another way to control access, but is not meant for service-level restrictions/accesses

Agreed, I see the same is applied here also https://github.ibm.com/dreadnought/dreadnought-account-setup-module/blob/main/main.tf.

Looks good, we should just add an update in main and example readme file describing this add-on feature.

**Comment by maheshwarishikha** [comment]
Please link Git issue with PR, it becomes handy if we need more info.
I checked the [issue 7468](https://github.ibm.com/GoldenEye/issues/issues/7468) description, CBR zones are required as an alternate to `allowed_ip_addresses` feature. Where are we using zone for `allowed_ip_address`?

**Comment by MatthewLemmond** [comment]
@Ak-sky @maheshwarishikha I've updated the module to add the names of the cbr zones that get created to the IP address list as discussed earlier in the week

**Review by maheshwarishikha — DISMISSED** [review]

**Review by maheshwarishikha — APPROVED** [review]

**Review by ocofaigh — CHANGES_REQUESTED** [review]
Please expose CBR feature in `solutions/fscloud` too

**Pull request merged**
